### ISSUE TITLE
Define Sara's hurt blobs.

### ISSUE THREAD

**Issue by jagoly** [jagoly/SuperTuxSmash#3]
Sara needs to have her hurt blobs defined. The way that these will work is they need to be defined in the transformation spaces of specific bones in her armature. This way, they can simply be transformed using the same armature used for animations.

So each hurt blob would consist of the index of the bone it is attached to, an origin relative to that bone (open the Sara_Core.blend file to check out the bone orientations and positions), and of course the radius of the sphere.

This should be something @CalmUnicorn can do, I can explain how the bone transformations work if that'd help.

**Comment by jagoly** [comment]
hehehe... whoops

I actually forgot that I rewrote the armature system a while ago. The positions of the blobs need to be specified relative to the REST POSE, not the individual bones. This makes things much easier - just put the blobs where they should be on the rest pose in object space, give them an index of a bone to attach to, and bam, they'll get transformed.

**Comment by ghost** [comment]
So what is an hurt blobs for you? Because I've been googling like crazy and I did not find anything.


Is it those invisible sphere that set the damage allocated to the player in function of which sphere we hit? 

like this : 
![image](https://user-images.githubusercontent.com/16458298/28380317-e60de7c2-6c84-11e7-8c20-c703e8f39a3b.png)

**Comment by jagoly** [comment]
Yes, exactly. Except in smash, all boxes (blobs) receive the same amount of
damage.

**Comment by ghost** [comment]
Okay nice, if you can just explain me a bit how you wan't me to integrate the hitbox in STS it would be appreciated.


I was thinking, since we are not making any kind of fps or any game that require lot's of precision we could just put one big box that could adapt the dimension if the player crounch or anything like that. In addition of making the integration of the hitbox faster (and the whole game development process faster) it would probably ask a bit less unecessary horse power to make the game run.

**Comment by jagoly** [comment]
actually, the hitboxes/hitbubbles do need to be fairly accurate for a
fighting game. Otherwise you get cases of "what!? but they didn't even hit
me!" or "what!? I hit him!", etc.

Performance is actually not likely to be an issue. That's why we are using
spheres only. Sphere/Sphere intersection tests are VERY cheap, just a few
subtractions and a multiplication.

You can see for example the shapes used in Smash
https://www.ssbwiki.com/Marth_(SSBM)/Hitboxes. Smash does also have
capsules, but a line of spheres is a close enough approximation of that.

**Comment by jagoly** [comment]
done in 24cd9eee8ee46fbf208fdd79b321f12574a914bf
